### ISSUE TITLE
Traduções Clérigos (sim, mais propostas)

### ISSUE THREAD

**Issue by Canato** [Treeofsavior/PortugueseTranslation#101]
Primeiro, prazer! Sou Canato, entusiasta,

Desculpa retomar nessa discussão, li hoje que isso já foi feito por esses dias, mas queria propor algumas mudanças que se mantiveram os nomes no clérigo. E estou pondo aqui para pode explicar cada:

==Krivis -> 
Realmente não achei nada bom e "brasileiro" sobre um sacerdote do fogo..
O "Melhor" seria.. Angra, deusa do fogo tupi-guaraní... 
Caco e Erictònio são filhos do deus do fogo/vulcão da mitologia grega..

"Krivis are priests who use divine fire to help allies recover or to deal massive damage to the enemy."

==Bokor -> Voduns/Bokonon  ou Axogun* (opção, mais "BR")
*Primeiro pensei em usar camdomblé, mas acho que vai dar treta por que as pessoas conhecem pouco da religião, então usar os termos mais a fundo, mais perto do "português" possível. O que acham??

"Bokor is a class which uses Voodoo skills." (voodoo -> vudu -> Camdomblé no brasil)

Hierarquia:
Bokonon - Sacerdote do vodum Fa equivalente ao Babalawo
Doté - Sacerdotes (homens) da família de Sogbo e Doné sacerdotisas (mulheres). Esse título é usado no Terreiro do Bogum, onde também são usados os títulos Gaiaku e Mejitó. Similar à Iyalorixá.
Noche - Sacerdotisas do Jeje-Mina.
Vodúnsi - após 1 ano da iniciação.
Kajekaji - iniciado que ainda não completou o ciclo de obrigações.

Mawu é o ser supremo dos povos Ewe e Fon, que criou a terra e os seres vivos e engendrou os voduns, divindades que a ("Mawu" é do gênero feminino) secundariam no comando do universo. Ela é associada a Lissá, que é masculino, e também corresponsável pela criação, e os voduns são filhos e descendentes de ambos. A divindade dupla Mawu-Lissá é intitulada Dadá Segbô

==Dievdirbys -> Rapanui
O jogo BR seria para toda America Latina, com isso cheguei em pesquisa aos Rapanui´s que foram o povo que construiu as "estátuas sagradas" Moai (na ilha de páscoa)
"Dievdirbys is a Cleric-type class which is specialized in making diverse types of wooden statues."

E ainda: Diácono...
Diácono é a função na qual o membro é escolhido para auxiliar nos serviços materiais da Igreja. Sendo indicado pelo Pastor Dirigente.

==Sadhu - > Transcendente
Sadhu can use out-of-body skills.

Transcendente, aquele que transcende o corpo (viaja com a alma), entre outras coisas,

**Comment by evtutchenko** [comment]
Não acredito que traduções de classes com nomes não-inglês seja uma opção.

**Comment by evtutchenko** [comment]
Localização é adaptar o conteúdo para que ele por completo fique familiar à outra cultura. No caso, muito se perde da obra original na execução de uma localização.

Na tradução o que ocorre é apenas uma tentativa de passar para outra língua o mesmo conteúdo sem alterações em seu significado.

**Comment by Arkadel** [comment]
As classes não foram votadas em definitivo, certamente mais pessoas poderão votar em um termo definitivo no futuro, é aquela questão, não faz sentido uma tradução agradar a minoria, e a galera aqui traduzindo, eu inclusive, somos a minoria da grande comunidade que poderá usufruir disso. Então é isso, vai haver votações mais sérias e definitivas, até se obter o denominador comum. Agradeço por sua preocupação com isso, diantemão.

Quanto as sugestões, talvez algumas delas possam ser incluídas nas opções. Mas realmente não encorajamos mudanças de nomes senão o inglês, porque se trata de uma tradução "english to portuguese". Há valores culturais muito bem embasados por trás de praticamente todas elas.

O Krivis se tornar de uma naturalidade grega é algo que não se encaixa, pois eles são oriundos da cultura lituânia. Eu vou passar links do wikipédia mesmo, porque eu sei que são fontes vaguíssimas, mas pelo menos se conta o básico de cada coisa. Sobre o Krivis: https://lt.wikipedia.org/wiki/Krivis

O Bokor já em caso a se pensar, entretanto os Bokor são mais focados especificamente em magia negra (pode-se considerar um tipo de umbandista, no link cita a camboja: https://pt.wikipedia.org/wiki/Bokor

Quanto aos Dievdirbys, eu realmente não consigo achar nenhuma fonte cultural, senão o próprio Tree of Savior. Já disseram que se tratam de "escultores divinos" de alguma cultura (talvez morta, não sei). Mas sua opinião a respeito deles (Rapanui) realmente me faz sentido, apesar de eu achar melhor deixar como está atualmente, e pela falta de necessidade de mudar um nome já praticamente conhecido pelos players no jogo por outro que poderiam estranhar. Entretanto, não exclui o fato de que pode entrar em uma discussão e votação sem problemas, afinal todos votarão. O mesmo vale para Diácono e Sadhu.

**Comment by evtutchenko** [comment]
Dievdirbys são lituanos que talham em madeira imagens cristãs.

**Comment by fabiohenm** [comment]
Acho que isso tira muito do conteúdo do jogo. As classes mais culturais foram feitas para ficarem dessa forma e não sofreram alterações nas outras traduções. Não cabe a nós alterar a ideia original das classes. Krivis é um sacertode do paganismo báltico, que é o foco central do jogo. Seria muito estranho tentar mudar isso. Os termos em lituano em especial nesse jogo nós fazemos o possível para manter como no original.

O mesmo vale para as outras classes. Não cabe a nós alterar a ideia original na tradução, pelo contrário, queremos manter o máximo do conteúdo original e apenas transmiti-lo em português. Não estamos aqui para ser artistas, idealizadores, nem nada do tipo, somos tradutores, e acho que é isso que a comunidade brasileira esperar da tradução. Não conheço nenhuma tradução de outros jogos que alteraram o contexto das coisas para se encaixar em algum tipo de mitologia local.

**Comment by evtutchenko** [comment]
@fabiohenm Exatamente minha visão. Adaptar o conteúdo para uma realidade sulamericana só vai ferir o jogo.

**Comment by fabiohenm** [comment]
Outra coisa sobre o Krivis: suas habilidades estão cheias de simbolismo nas animações, como o Austras Koks e o Zalciai, que são símbolos que pertencem reconhecidamente ao paganismo lituano. O Dievdirbys também tem a habilidade de esculpir a Austras Koks, e as deusas do jogo, que são inspirados eu figuras da mitologia lituana.

**Comment by evtutchenko** [comment]
O próprio design das costumes dos personagens teria de ser alterado se for pra adaptar por completo.

**Comment by Canato** [comment]
Opa!

Agradeço pelas respostas, até me ajudou muito a me situar melhor. Então enquanto não estar mais familiarizado, vou me atentar apenas a traduções diretas e dar opinião nas discussões ^^

Ainda estou entendo sobre questão de baixar e avisar onde estou trabalhando (commit, pull e push são easy). Se alguém quiser "ensinar" que não achei nenhum guia total, agradeço. Para evitar problemas ^^ Valeu pessoal

(fechar por enquanto, quando ressurgir essa discussão pode ser visto o que foi dito.)
