### ISSUE TITLE
Duvida sobre nome de monstros!

### ISSUE THREAD

**Issue by Mindigow** [Treeofsavior/PortugueseTranslation#118]
Ola pessoal, eu estava traduzindo algumas partes dos etc., porém me deparei com nome de monstros... e acabei pulando e não traduzi esses nomes, traduzi apenas a descrição deles, porém eu vi que tem alguns monstros que teriam uma tradução e outros não.

Como proceder?

**Comment by yalmeida69** [comment]
Coloca "#pending" do lado do nome pra facilitar a tradução num segundo momento.

**Comment by Mindigow** [comment]
ok
