### ISSUE TITLE
Duvida

### ISSUE THREAD

**Issue by billarkwright** [Treeofsavior/PortugueseTranslation#126]
Não entendi o porque da tradução que eu tinha feito na UI foi retirada... Na última versão do arquivo as traduções das linhas que eu fiz e que foram dadas merge estão em branco... Só acho que quem fez o pullrequest e a propria IMC não viu que o arquivo não estáva atualizado ou com conflitos...

**Comment by yalmeida69** [comment]
A UI já tinha sido traduzida 100% pelo @BrasilToS , como ele já tinha dito em issues passados. Foi alguma correção em cima disso ou foi retrabalho mesmo?

**Comment by billarkwright** [comment]
As linhas que eu fiz o pullrequest foram exatamente as linhas que não estavam traduzidas, eu verifiquei todos os pullrequest, os que foram dados merges e os que não foram.. E como ele já tinha dado o pullrequest da linha 1000+, foi a que traduzi, foram umas 50 linhas apenas.

**Comment by yalmeida69** [comment]
E o seu PR ainda tá aberto ou foi fechado sem merge?

**Comment by billarkwright** [comment]
O primeiro já tinha dado merge... Verifica no histórico.
Mas tudo bem, se já foi tudo traduzido então vamos esperar o BrasilToS atualizar tudo.
