### ISSUE TITLE
Tamanho de linha

### ISSUE THREAD

**Issue by samosaara** [Treeofsavior/PortugueseTranslation#147]
Algumas linhas acabam com o tamanho final completamente discrepante do original e assumindo que '{n1}' seja um pula linha manual, será que devíamos nos preocupar com o tamanho da frase pra não sair fora do balão de fala? Ou será que a linha pula sozinha e que o {n1} é só pra forçar o pulo de linha

**Comment by yalmeida69** [comment]
O comando é {nl}, referente a "newline". E acredito que temos que nos preocupar com o tamanho sim. Mas seria legal ter um posicionamento dos devs sobre o tamanho ideal. Talvez no github da tradução KOR-ENG tenha essa informação.

**Comment by samosaara** [comment]
Então, andei pesquisando sobre o alfabeto coreano e, tive a quase certeza que os balões tinham de ter tamanhos dinâmicos por que as letras coreanas são na verdade sílabas, por exemplo: 
>Cada um dos Jamos representa uma sílaba e o conjuto de sílabas forma uma palavra. Dessa maneira, ainda que 한 possa parecer como uma letra ou caractere, na verdade é uma silaba composta por três letras distintas: ㅎ (h) +ㅏ(a) + ㄴ (n), logo 한 = han!
Isso tornaria o problema ainda pior para coreano>inglês. Talvez até impossível sem baloes dinâmicos. mas não tenho certeza.

**Comment by samosaara** [comment]
Alguma luz? ;-;

**Comment by yalmeida69** [comment]
Já procurou algo sobre aqui? https://github.com/Treeofsavior/EnglishTranslation

**Comment by samosaara** [comment]
Achei! E me surpreendeu. Sim tem um tamanho máximo de linha, mas me pareceu bem abrangente, a apenas em algumas exceções que a tradução seja EXTREMAMENTE maior não é preciso se preocupar.

Descobri tudo isso usando esse APP online feito por um dos contribuidores da tradução inglesa: http://vtange.github.io/TreeOfSaviorFormatter/  ele emula as caixas de diálogo, e as caixas flutuantes de descrição de Quest do jogo. É até uma ótima ferramenta de revisão. Devíamos colocar na wiki.
