### ISSUE TITLE
Erros por toda parte

### ISSUE THREAD

**Issue by faicciruz** [Treeofsavior/PortugueseTranslation#173]
Pessoal, a melhor forma de traduzir é aquela que você pode ver ao vivo como está ficando. Por isso talvez a minha tradução não seja aceita, não estou indo de forma linear, apesar disso ser o recomendado. Estamos em GIT e não em SVN, já passou dessa época.

Por outro lado, fazendo isso vi o tanto de erro que existe na tradução atual (não estou falando dos acentos):

~~$ nos nomes (por todos os lados)~~
![Erro1](http://i.imgur.com/Qnl382f.png)

Edit: $ Quer dizer que o texto já foi revisado, então não é um erro, embora muita coisa no arquivo não tenha sido revisada, até por que tá bem fácil achar erros.

{n1} 
![Erro2](http://i.imgur.com/2t6nJls.png)

Isso vai terminar atrasando o projeto, ainda mais com a falta de moderação oficial na parte Portuguesa.

**Comment by evtutchenko** [comment]
Claramente isso é uma incompatibilidade com acentos.

**Comment by faicciruz** [comment]
"Por outro lado, fazendo isso vi o tanto de erro que existe na tradução atual (**não estou falando dos acentos**)"

Level {Level}

**Comment by yalmeida69** [comment]
Eu já tinha até comentado aqui que o comando correto é "{nl}", de "newline", mas aparentemente alguns "{n1}" acabaram passando. Pelo menos esse é um erro fácil de corrigir. Quanto a parte de acentuação, a nossa tarefa é traduzir corretamente com acentos e tudo mais, e os devs da IMC que tem que se virar pra alterar a codificação dos caracteres ou a fonte do jogo pra suportar o que foi traduzido.

**Comment by faicciruz** [comment]
Você podia me adicionar no skype... kkk

Tem muita tradução pendente, só não são aplicadas porque o criador não deixou a autorização para isso.
