### ISSUE TITLE
Convenções/protocolos de tradução (LOCALIDADES)

### ISSUE THREAD

**Issue by dadaum** [Treeofsavior/PortugueseTranslation#19]
Galera segue o link
deixei aberto para escreverem suas propostas para cada um. Organização pessoal! não venham apagar propostas do colega e nem zoar o documento.
Os que tiverem com multiplas propostas serão votados posteriormente
https://docs.google.com/spreadsheets/d/1th3j0RNnGZJd3nN_zR5sXTlKy7S7Gz4Nfowiyg8PDik/edit?usp=sharing

**Comment by dadaum** [comment]
Alou teste

**Comment by yalmeida69** [comment]
Tamos aqui.

**Comment by fabiohenm** [comment]
Ótimo, podemos discutir agora as localidades do jogo.

**Comment by StikerSD** [comment]
Pronto.

**Comment by StikerSD** [comment]
Caramba fomos bem rápidos.

**Comment by dadaum** [comment]
Ok, eu estava pensando em fazer um arquivo no google drive com o nome de todas as localidades

Porquê são muitas.

**Comment by StikerSD** [comment]
E eu achando que fazer tradução era chato, kkk

**Comment by StikerSD** [comment]
@dadaum  Boa ideia.

**Comment by StikerSD** [comment]
@dadaum  Dropbox também é uma opção.

**Comment by dadaum** [comment]
O bom do drive é que o pessoal pode ficar alterando simultaneamente

**Comment by kaiqueamorim2** [comment]
tamo aqui

**Comment by dadaum** [comment]
um segundo...

**Comment by StikerSD** [comment]
@dadaum é verdade.

**Comment by dadaum** [comment]
onde está o arquivo com todas as localidades?

**Comment by StikerSD** [comment]
um segundo, temos que pegar na outra discussão.

**Comment by Arkadel** [comment]
É muita coisa. Isso sim vai dar trabalho. Mudei alguns pontos sob sugestão.

• West Siauliai Woods (Bosques Ocidentais de Siauliai)
• Klaipeda (Klaipeda)
• East Siauliai Woods (Bosques Orientais de Siauliai)
• Miner's Village (Vilarejo dos Mineradores)
• Crystal Mine (Mina de Cristal)
• Srautas Gorge (Desfiladeiro de Srautas)
• Gele Plateau (Planalto de Gele)
• Nefritas Cliff (Penhasco de Nefritas)
• Tenet Garden (Jardim de Tenet)
• Tenet Chapel (Capela de Tenet)
• Veja Ravine (Ravina de Veja)
• Vieta Gorge (Desfiladeiro Vieta)
• Cobalt Forest (Floresta de Cobalto)
• Septyni Glen (Vale Estreito)
• Gate Route (Rota do Portão)
• Sirdgela Forest (Floresta Sirdgela)
• Kvailas Forest (Floresta Kvailas)
• Gateway of the Great King (Portões do Grande Rei)
• Ramstis Ridge (Cume de Ramstis)
• Overlong Bridge Valley (Longínquo Vale da Ponte)
• Akmens Ridge (Cume de Akmens)
• Tiltas Valley (Vale de Titas)
• Rukas Plateau (Planalto Rukas)
• King's Plateau (Planalto do Rei)
• Zachariel Crossroads (Cruzamento de Zachariel)
• Royal Mausoleum (Mausoléu Real)
• Gytis Settlement Area (Área de Assentamento de Gytis)
• Baron Allerno (Barão Allerno)
• Myrkiti Farm (Fazenda Myrkiti)
• Aqueduct Bridge Area (Área da Ponte Arqueduto)
• Tenants Farm (Fazenda de Tenants)
• Stele Road (Estrada de Stele)
• Goddess' Ancient Garden (Jardim Antigo da Deusa)
• Escanciu Village (Vilarejo de Escanciu)
• Fedimian Suburbs (Subúrbios de Fedimian)
• Fedimian (Fedimian)
• Entrance of Kateen Forest (Entrada da Floresta Kateen)
• Owl Burial Ground (Solo da Coruja Enterrada)
• Poliskis Forest (Floresta Poliskis)
• Saknis Plains (Planícies Saknis)
• Mage Tower (Torre do Mago)
• Dvasia Peak (Pico Dvasia)
• Sunset Flag Forest (Floresta da Bandeira do Amanhecer)
• Starving Demon's Way (Caminho do Demônio Faminto)
• Pilgrim Path (Caminho do Peregrino)
• Altar Way (Caminho do Altar)
• Forest of Prayer (Floresta dos Oradores)
• Apimesti Crossroads (Cruzamento do Apimesti)
• Main Chamber (Câmara Central)

**Comment by yalmeida69** [comment]
"Forest of Prayer" tá mais pra "Floresta da Oração".

**Comment by dadaum** [comment]
Sim mas ta incompleto esse quye você passou

**Comment by Arkadel** [comment]
Bem incompleto, tem nem a metade. Talvez termine dado algumas horas. Mas os termos mais comuns.

**Comment by StikerSD** [comment]
http://www.tosbase.com/game/world-map/

**Comment by StikerSD** [comment]
tem o mapa mundi do jogo

**Comment by StikerSD** [comment]
espero que tenha tudo.

**Comment by Arkadel** [comment]
Tem tudo, to me baseando aí

**Comment by dadaum** [comment]
sim mas eu precisava de uma lista

**Comment by StikerSD** [comment]
Alguém podia redigir tudo

**Comment by gustavo02** [comment]
E se estiverem procurando a lista dos locais nos scripts, ela fica lá no "ETC", a partir da linha 1100 e pouco.

**Comment by StikerSD** [comment]
West Siauliai Woods
Lv 1
Klaipeda
Lv 0
East Siaulia Woods
Lv 6
Miners' Village
Lv 12
Srautas Gorge
Lv 26
Grynas Trails
Lv 336
Grynas Training Camp
Lv 340
Grynas Hills
Lv 344
Gytis Settlement Area
Lv 69
Crystal Mine 1F
Lv 16
Gele Plateau
Lv 29
Pilgrimage Trail 41_4
Lv 350
Monastery 41_6
Lv 359
Pilgrimage Trail 41_5
Lv 356
Bracken Forest 43_4
Lv 364
Myrkiti Farm
Lv 86
Baron Allerno
Lv 84
Veja Ravine
Lv 46
Entrance of Kateen Forest
Lv 106
Nefritas Cliff
Lv 32
Pilgrimage Trail 41_1
Lv 343
Pilgrimage Trail 41_2
Lv 346
Pilgrimage Trail 41_3
Lv 353
Bracken Forest 43_1
Lv 355
Bracken Forest 43_3
Lv 361
Aqueduct Bridge Area
Lv 89
Tenants Farm
Lv 92
Vieta Gorge
Lv 49
Owl Burial Ground
Lv 109
Tenet Garden
Lv 35
Tenet Chapel B1
Lv 40
Bracken Forest 42_1
Lv 363
Bracken Forest 42_2
Lv 367
Bracken Forest 43_2
Lv 358
Limestone Cave 55-1
Lv 367
Greene Manor
Lv 149
Demon Prison District 1
Lv 151
Cobalt Forest
Lv 52
Poslinkis Forest
Lv 112
Saknis Plains
Lv 114
Limestone Cave 52_1
Lv 371
Coral Plains 44_3
Lv 378
Shaton Farm
Lv 152
Dina Bee Farm
Lv 160
Septyni Glen
Lv 55
Gate Route
Lv 58
Dvasia Peak
Lv 120
Sunset Flag Forest
Lv 123
Gateway of the Great King
Lv 58
Ramstis Ridge
Lv 61
Coral Plains 44_2
Lv 381
Coral Plains 44_1
Lv 385
Shaton Reservoir
Lv 155
Vilna Forest
Lv 163
Uskis Arable Land
Lv 166
Spring Light Woods
Lv 169
Sirdgela Forest
Lv 61
Kvailas Forest
Lv 64
Overlong Bridge Valley
Lv 64
Underground Passage 3
Lv 0
Mokusul Chamber
Lv 188
Raukime Reservoir
Lv 179
Glade Hillroad
Lv 173
Viltis Forest
Lv 176
Passage of the Recluse
Lv 0
Akmens Ridge
Lv 67
Monastery 35_4
Lv 229
Underground Grave of Ritinis
Lv 191
Videntis Shrine
Lv 194
Valius' Eternal Resting Place
Lv 197
Tyla Monastery
Lv 183
Tiltas Valley
Lv 69
Galeed Plain
Lv 227
Monastery 35_3
Lv 226
Istora Ruins
Lv 176
Namu Temple Ruins
Lv 172
Nuoridin Falls
Lv 168
Stele Road
Lv 96
Zachariel Crossroads
Lv 78
Royal Mausoleum 1F
Lv 81
Rukas Plateau
Lv 73
Fasika Plateau
Lv 230
Siauliai 35_1
Lv 223
Coral Plains 35_2
Lv 220
Goddess' Ancient Garden
Lv 99
Escanciu Village
Lv 103
King's Plateau
Lv 76
Mullers Passage
Lv 0
Manahas
Lv 234
Coral Plains 32_1
Lv 216
Fedimian Suburbs
Lv 107
Mage Tower 1F
Lv 113
Genra Field
Lv 237
34_1 Grand Fruit Forest
Lv 235
제라하
Lv 238
Coral Plains 32_2
Lv 213
Fedimian
Lv 0
Starving Demon's Way
Lv 121
Pilgrim Path
Lv 124
Altar Way
Lv 127
Forest of Prayer
Lv 130
Main Chamber
Lv 137
34_3 Grand Fruit Forest
Lv 242
Bellai Forest
Lv 210
and entered the Mausoleum of Karail
Lv 251
Sienakal Graveyard
Lv 247
Apsimesti Crossroads
Lv 133
Feretory Hills
Lv 197
Sutatis Trade Route
Lv 200
Seiru Forest
Lv 207
Underground Passage 4
Lv 0
Roxona Market
Lv 187
Verkti Square
Lv 184
Downtown
Lv 193
Dingofasil District
Lv 247
Coastal Fortress
Lv 244
Mochia Forest
Lv 203
Catacombs 25_4
Lv 281
Stogas Plateau
Lv 279
Ruklys Street
Lv 190
Ibre Plateau
Lv 260
Inner Enceinte District
Lv 196
Sentry Bailey
Lv 200
Fort of the Land 30_1
Lv 251
Fort of the Land 30_2
Lv 255
Maple Forest 24_2
Lv 309
Maple Forest 24_1
Lv 306
Maple Forest 24_3
Lv 303
Maple Forest 25_3
Lv 285
Grand Yard Mesa
Lv 264
Sventimas Exile
Lv 268
Isolated Plateau
Lv 279
Fort of the Land 30_3
Lv 259
Monastery 22_5
Lv 331
White Tree 56_1
Lv 316
White tree 23_3
Lv 312
Maple forest 23_2
Lv 308
Maple Forest 25_2
Lv 288
Mesafasla
Lv 276
Kadume Cliff
Lv 272
Steel Heights
Lv 275
Kalejimas Visiting Room
Lv 283
Monastery 22_4
Lv 328
White tree 22_3
Lv 325
White tree 22_2
Lv 322
White tree 23_1
Lv 305
Maple Forest 25_1
Lv 291
3cm lake 26_2
Lv 395
3Cm lake 83
Lv 383
3Cm lake 84
Lv 386
White tree 22_1
Lv 318
White tree 21_2
Lv 309
Kule Peak
Lv 300
3cm lake 26_1
Lv 399
3Cm lake 86
Lv 394
3Cm lake 85
Lv 390
Fantasy Library 48_1
Lv 317
White tree 21_1
Lv 312
Castle Field 20_3
Lv 448
Castle Field 20_1
Lv 442
Castle 93
Lv 408
3Cm lake 87
Lv 398
3cm lake 27_2
Lv 437
3cm lake 27_3
Lv 441
Castle Field 20_4
Lv 451
Castle Field 20_2
Lv 445
Castle 94
Lv 411
Castle 95
Lv 414
Star Tower 88
Lv 403
3cm lake 27_1
Lv 434
Castle Dungeon 19_2
Lv 432
Closed Town 53_1
Lv 459
Closed Town 20_5
Lv 454
Closed Town 20_6
Lv 457
Castle 96
Lv 417
Castle 97
Lv 420
Closed Town 103
Lv 454
Orsha
Lv 0
Castle 98
Lv 420
Castle 101
Lv 424
Castle Dungeon 19_1
Lv 429
Closed Town 107
Lv 467
Closed Town 105
Lv 463
Closed Town 104
Lv 457
Castle 99
Lv 427
Castle 100
Lv 431
Castle 102
Lv 435
Closed Dungeon 108
Lv 472
Closed Town 106
Lv 460
Closed Town 18_1
Lv 467
Closed Town 18_2
Lv 470

**Comment by StikerSD** [comment]
deixa pra lá ia ficar muito confuso

**Comment by StikerSD** [comment]
se quiserem usar essa que eu colei ai, mas acho que esta muito confusa

**Comment by dadaum** [comment]
ta sussa @StikerSD ficou bom

**Comment by dadaum** [comment]
eu arrumo

**Comment by StikerSD** [comment]
eu passei o mouse no mapa e copiei

**Comment by StikerSD** [comment]
kkk

**Comment by yalmeida69** [comment]
Tem mapa que eles nem criaram o nome direito ainda...

**Comment by StikerSD** [comment]
@yalmeida69 os que eles não terminaram esta escrito ''close''.

**Comment by StikerSD** [comment]
você tem acento ou não? Sempre me confundo quanto à isso.

**Comment by dadaum** [comment]
https://docs.google.com/spreadsheets/d/1th3j0RNnGZJd3nN_zR5sXTlKy7S7Gz4Nfowiyg8PDik/edit?usp=sharing

**Comment by StikerSD** [comment]
Nossa ficou muito bem arrumado.

**Comment by dadaum** [comment]
Galera segue o link
deixei aberto para escreverem suas propostas para cada um. Organização pessoal! não venham apagar propostas do amiguinho e nem zuar o documento.

**Comment by StikerSD** [comment]
Posso escrever a minha?

**Comment by yalmeida69** [comment]
Lv 251 : and entered the Mausoleum of Karail

Pensa numa tradução torta...

**Comment by dadaum** [comment]
a vontade

**Comment by StikerSD** [comment]
O nome do lugar é Veja Ravine, eu traduzi para Veja Ravina, ficou muito tosco alguém tem uma ideia melhor?

**Comment by kaiqueamorim2** [comment]
Ravina Veja

**Comment by dadaum** [comment]
Ravina Veja ou Ravina de Veja...caso Veja um nome

**Comment by fabiohenm** [comment]
Acho que não tem como ficar um nome que não seja tosco com "Veja" no meio. :stuck_out_tongue:

**Comment by dadaum** [comment]
Galera chegou ccliente na empresa, já volto aqui

**Comment by fabiohenm** [comment]
Pessoal, recomendo que façam as traduções em algum software de edição de texto como o Word e passem o corretor ortográfico só por via das dúvidas. Também passei a fazer isso pra salvar o arquivo, quase perdi uma edição aqui quando travou o firefox.

**Comment by NickStarlight** [comment]
Pessoal, fiz grande parte da identificação do gênero dos NPCS Mestres.
https://github.com/Treeofsavior/PortugueseTranslation/wiki/G%C3%AAnero-dos-NPC's

**Comment by fabiohenm** [comment]
@NickStarlight
Bom trabalho!

**Comment by StikerSD** [comment]
Gente, vou ter que sair aqui depois eu volto, até mais.

**Comment by StikerSD** [comment]
Na realidade eu tenho que estudar, de vez em quando dou uma olhada aqui.

**Comment by NickStarlight** [comment]
Adicionei as traduções de cada npc na wiki

**Comment by fabiohenm** [comment]
Quanto aos mapas, acho que no momento só temos até o mapa nível 197 no jogo, então não se preocupem muito em traduzir tudo.

@StikerSD
Até breve.

**Comment by StikerSD** [comment]
Eu traduzi muitos, alguns não consegui traduzir.

**Comment by Arkadel** [comment]
Bem, minha parte eu terminei

**Comment by kaiqueamorim2** [comment]
eu ajudei pra caramba dando outras opções de tradução na coluna B

**Comment by kaiqueamorim2** [comment]
B não, C

**Comment by kaiqueamorim2** [comment]
Acho que os mapas a galera ja completou

**Comment by yalmeida69** [comment]
Ficou bem bom. Só temos que decidir agora entre as variações

**Comment by StikerSD** [comment]
Todos os mapas que eu traduzi foi na coluna A,

**Comment by StikerSD** [comment]
@yalmeida69 Sim.

**Comment by Arkadel** [comment]
Olha, faltou uma cidade lá, talvez seja e do nome coreano. A capital do reino, e última cidade do jogo se chama "Orsha".

**Comment by yalmeida69** [comment]
Tô apagando as sugestões repetidas pra cada localidade, tem problema?

**Comment by StikerSD** [comment]
@yalmeida69 acho que não.

**Comment by NickStarlight** [comment]
Pessoal, irei sair aqui, tenho bastante coisa a fazer, boa sorte nas traduções, até o/

**Comment by Arkadel** [comment]
Estou realmente em dúvidas de como ponho traduções de quests aqui.

**Comment by kaiqueamorim2** [comment]
Tem que polir as traduções, ta faltando muito acento e tem muita palavra errada

**Comment by yalmeida69** [comment]
Vai ter proofreading depois, eu posso fazer a revisão de algumas coisas.

**Comment by dadaum** [comment]
Galera vou deixar o prazo pra fazer as votações as 19

**Comment by fabiohenm** [comment]
Arkadel, tem que editar os textos no arquivo, clicando no lápis de edição ao abrir o arquivo na página inicial e deixando a tradução paralela à do arquivo em inglês. Veja se consegue lá. Não atualiza de imediato, a IMC vai meio que retificar as mudanças de tempo em tempo.

**Comment by fabiohenm** [comment]
Eu abri um issue para todas as edições do ITEM_BP.tsv. Espero que não se importem. Recomendo que criemos issues únicas para cada arquivo da página inicial se não a coisa vai ficar muito bagunçada.

**Comment by dadaum** [comment]
Galera estarei fazendo as votações para as regioes. Vou criar uma votação unica para todos os nomes ok?

**Comment by yalmeida69** [comment]
https://github.com/ensata/TreeOfSavior-en-research

Referência interessante pra decidirmos os nomes.

**Comment by dadaum** [comment]
Nooossa eu tava procurando exatamente isso, vou extender a pesquisa para as 20

**Comment by dunia01** [comment]
Temos que ver como ficarão as classes também.

**Comment by dadaum** [comment]
Já foi feito @dunia01 , você pode checar em https://github.com/Treeofsavior/PortugueseTranslation/wiki/Tradu%C3%A7%C3%A3o-das-classes

**Comment by dadaum** [comment]
Galera eu vou deixar a votação para amanhã, com esse dados que o pessoal passou tem muita informação a mais que brotou

**Comment by heytrevor** [comment]
"Tenet" significa Dogma, princípio, fundamento...coloquei opçoes de traduções no Docs. Não que eu as ache tão boas, mas acho que poderiamos pensar juntos numa tradução pra Tenet, já que no fundo existe um significado...

**Comment by Arkadel** [comment]
@heytrevor Ainda deve ter o arquivo do drive por aí, você pode modificar no arquivo essa tradução

**Comment by heytrevor** [comment]
@Arkadel não é o docs do autor da postagem? Se for eu coloquei lá. Se não for, não achei '-' hauhau

**Comment by Arkadel** [comment]
Sim, é o link da primeira postagem

**Comment by RicardoRFaria** [comment]
Pessoal, não participei da discussão, mas vi que existem várias propostas, existe algum cronograma para escolher a que usaremos na tradução?

**Comment by Arkadel** [comment]
Também fiquei na dúvida, pois pretendo colar as soluções atuais pro tópico de quests pra ajudar quem está fazendo. É bom eliminarmos esse problema logo de uma vez pra agilizar o trabalho dos tradutores.

**Comment by yalmeida69** [comment]
O @dadaum ficou de fazer hoje a votação entre as variações que surgiram ontem.

**Comment by yalmeida69** [comment]
@heytrevor Acredito que a IMC não vai aceitar traduções das palavras em lituano, já que elas que formam boa parte da lore do jogo e são o que dão aquele ar de "mundo diferente" do nosso. Tanto que a tradução KOR-ENG manteve as palavras, apenas romanizando a escrita de acordo com a língua. Vale lembrar que a tradução é Inglês-Português, então acho que qualquer coisa que não for inglês deve ser mantida do jeito que está.

**Comment by heytrevor** [comment]
@yalmeida69 Eu li nas guidelines mas..Tenet, é ingles (deriva do latim), Não sei como é em lituano, pode ser similar mas de qualquer forma é uma palavra inglesa também.

**Comment by Arkadel** [comment]
Sim, eu desconhecia essa palavra, vi no dicionário aqui e tá certinho. Tenet: princípio, dogma e doutrina (acredito que dogma seja o melhor)

**Comment by heytrevor** [comment]
Ficaria algo como "Jardins dos dogmas" "jardins dos princípios" e/ou "Capela dos Dogmas" "Capela dos princípios".

**Comment by fabiohenm** [comment]
Também gostei de Dogma.

**Comment by dadaum** [comment]
E ai galera, pode fechar?

**Comment by yalmeida69** [comment]
Mas vai fechar como com tantas variações?

**Comment by heytrevor** [comment]
@dadaum eu e o @guipaz estamos montando uma enquete no Google Drive, para votarmos algumas traduções que consideramos mais sensíveis. E assim irmos fechando algumas convençoes. Não incluímos os mapas justamente porque você estava fazendo e porque é muuuito mais coisa. Após a gente fechar algumas coisas preliminares já queremos lançar ela aqui e também pra comunidade de ToS brasileira mundo afora para termos uma idéia do que a galera acha.
De qualquer forma se precisar de alguma ajuda, estamos aí. Acho que o ideal tanto na sua, quanto na nossa enquete é reunir o que der da melhor forma e lançar o quanto antes, porque conforme mais pessoas vão vendo mais idéias vão surgindo, e também não adianta esperar MUITO pra juntar algo porque sempre vai tá surgindo coisa nova e a gente vai ajeitando. Não sei tambem se esse seria o caso dos mapas, mas seria sim possível creio eu, ao menos alguns deles mais complicadinhos.
Não sei se concordas comigo, mas novamente, vamos juntos nessa.

**Comment by dadaum** [comment]
Ola @heytrevor, a votação das classes já foi feita na issue #4 , deixamos no momento os nomes descritos na wiki para posteriormente pedir para comunidade votar.

**Comment by dadaum** [comment]
@yalmeida69  vou fechar para votação.

**Comment by Arkadel** [comment]
Por favor, divulguem ao máximo de pessoas.
