### ISSUE TITLE
Money/Units in Brazilian Format

### ISSUE THREAD

**Issue by wevtimoteo** [Treeofsavior/PortugueseTranslation#27]
Pessoal, algo que tem me incomodado bastante durante o jogo é que o dinheiro é apresentado sem o  separador de milhares.

Ex.:

```
5000 => 5.000
900000 => 900.000
7450000 => 7.450.000 
```

Poderíamos criar uma convenção para o que o dinheiro, assim como qualquer unidade, seja padronizado no nosso formato brasileiro na nossa tradução.

O que acham?

**Comment by fabiohenm** [comment]
Sim, claro, acho o mais sensato. Pontos para milhares, vírgulas para decimais.

**Comment by RicardoRFaria** [comment]
Acredito que só conseguiremos atualizar isso nos valores presentes em textos, uma vez que os valores que são apresentados dinamicamente dependem dos devs.

**Comment by wevtimoteo** [comment]
Bem lembrado @RicardoRFaria, vi que em muitos lugares da tradução o valor está estático. Como fica isso? Não deveria ser alguma variável na tradução que represente o valor?

**Comment by wevtimoteo** [comment]
Assim o `parse` do valor fica por conta dos devs

**Comment by RicardoRFaria** [comment]
Pois é, na minha opinião é uma falha de design do código, uma vez que o valor apresentado pode ser um e a execução ser outro, mas não é algo que esteja no nosso alcance.
Apenas conseguiremos seguir o padrão na tradução das mensagens mesmo.

**Comment by wevtimoteo** [comment]
Existe algum canal que podemos utilizar para questionar a @imcgames a respeito?

**Comment by RicardoRFaria** [comment]
Não estou ciente, mas creio que pela estrutura dos arquivos de mensagens, não seja uma opção viável.

**Comment by wevtimoteo** [comment]
Faz sentido, por ora deveríamos seguir o mesmo padrão que outros idiomas estão seguindo.


Estou fechando a issue enquanto não temos nenhum feedback em relação a isso.
