### ISSUE TITLE
Convenções - CLASSES

### ISSUE THREAD

**Issue by guipaz** [Treeofsavior/PortugueseTranslation#51]
Pessoal, comecei a realizar a tradução de algumas linhas e me deparei com o nome de uma classe (Chronomancer).

Deveríamos criar um arquivo no drive para também postar propostas para as mesmas? Acho que seria interessante visto que são palavras-chave do jogo que não são necessariamente da língua inglesa.

-----

Não era do meu conhecimento a discussão anterior, segue link para quem estiver procurando como eu estava:
https://github.com/Treeofsavior/PortugueseTranslation/wiki/Tradu%C3%A7%C3%A3o-das-classes

**Comment by yalmeida69** [comment]
Cara, vai na wiki que já tem um artigo pra isso.

https://github.com/Treeofsavior/PortugueseTranslation/wiki/Tradu%C3%A7%C3%A3o-das-classes

**Comment by yalmeida69** [comment]
Essa discussão sobre as classes foi feita ontem.

**Comment by guipaz** [comment]
Perfeito yalmeida, peço desculpas pela confusão.

**Comment by fabiohenm** [comment]
Relaxa, você não estava aqui, não teria como saber. Esses nomes também ainda não são finais, mas é os que usaremos na tradução por agora.
