### ISSUE TITLE
Tradução dos Mestres

### ISSUE THREAD

**Issue by RicardoRFaria** [Treeofsavior/PortugueseTranslation#55]
Pessoal, notei que na wiki alguns mestres estavam invertidos utilizando "Mestre WTV" mas a maioria está "WTV Mestre". Atualizei para o padrão da maioria com mestre como segundo nome, será assim mesmo? Podemos convencionar?

**Comment by yalmeida69** [comment]
Eu acho que Mestre X fica melhor.

**Comment by RicardoRFaria** [comment]
Alguém pode criar uma pool para levantarmos isso?

**Comment by fabiohenm** [comment]
http://strawpoll.me/6045042

**Comment by Arkadel** [comment]
Fiz uma atualização lá de acordo com a votação por enquanto (também prefiro assim). Adicionei também Fencer que não estava na lista.

**Comment by RicardoRFaria** [comment]
Bom, como ninguem votou por Mestre depois, vou fechar isso aqui, e fica decidido.
